apiVersion: v1
kind: ConfigMap
metadata:
  name: order-ms-config
data:
  PORT: "6000"
  DB_HOST: "192.168.0.104"
  DB_PORT: "3306"
  DB_USER: "kubernetes"
  DB_NAME: "order_db_ms"
  AUTH_SERVICE_URL: "http://auth-service:3000"
  PRODUCT_SERVICE_URL: "http://product-service:5000"