apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ORDER_MS_NAME}
spec:
  replicas: ${REPLICA_COUNT}
  selector:
    matchLabels:
      app: ${ORDER_MS_NAME}
  template:
    metadata:
      labels:
        app: ${ORDER_MS_NAME}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ${ORDER_MS_NAME}
          image: ${DOCKER_IMAGE_URI}:${IMAGE_TAG}
          ports:
            - containerPort: ${CONTAINER_RUNNING_PORT}
          envFrom:
            - configMapRef:
                name: ${ORDER_MS_NAME}-config
            - secretRef:
                name: ${ORDER_MS_NAME}-secret